using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

// navius-wpf - a minimal copy-paste component registry CLI for Navius.Wpf.
//
//   navius-wpf list
//   navius-wpf add <name> --to <dir> --namespace <ns> [--root <repo>] [--registry <path>]
//   navius-wpf registry-sync [--root <repo>] [--registry <path>]
//
// `add` resolves registryDependencies transitively (so `add select` also brings `anchored-popup`
// and `core`) before copying a single file. This closure step exists because of a defect class
// found while hardening the sibling web CLI (Navius.Cli, in zits-helm): registry items vendored
// without their full dependency closure did not compile. tests/Navius.Wpf.Cli.Tests is the gate
// that would have caught it here - it runs `add` against a real temp project and shells
// `dotnet build` on the result.
//
// `registry-sync` scans src/Navius.Wpf.Primitives and src/Navius.Wpf.Ui and regenerates
// registry/registry.json deterministically. The registry is generated, not hand-authored:
// re-run `navius-wpf registry-sync` after adding a control family or styled item.

const string RegistrySchemaJson =
"""
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Navius.Wpf registry",
  "description": "Generated by `navius-wpf registry-sync`. Do not hand-edit registry.json - re-run the sync instead.",
  "type": "object",
  "required": ["name", "items"],
  "properties": {
    "$schema": { "type": "string" },
    "name": { "type": "string" },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "type", "title", "dependencies", "registryDependencies", "files"],
        "properties": {
          "name": { "type": "string", "description": "kebab-case item id, used on the CLI (`navius-wpf add <name>`)." },
          "type": { "type": "string", "enum": ["registry:core", "registry:primitive", "registry:styled"] },
          "title": { "type": "string" },
          "dependencies": { "type": "array", "items": { "type": "string" }, "description": "NuGet package ids required by this item." },
          "registryDependencies": { "type": "array", "items": { "type": "string" }, "description": "Other item names this item's source references; resolved transitively by `add`." },
          "files": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["path", "type", "target"],
              "properties": {
                "path": { "type": "string", "description": "Repo-root-relative source path." },
                "type": { "type": "string", "enum": ["registry:code", "registry:theme"] },
                "target": { "type": "string", "description": "Path under the consumer project's --to directory." }
              }
            }
          }
        }
      }
    }
  }
}

""";

string root = Directory.GetCurrentDirectory();
string? to = null;
string? ns = null;
string? registryPath = null;
var packageRoot = AppContext.BaseDirectory;
var rootExplicit = false;
var positional = new List<string>();

for (int i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--to":
            if (!TryReadOptionValue(args, ref i, out to)) return 1;
            break;
        case "--namespace":
            if (!TryReadOptionValue(args, ref i, out ns)) return 1;
            break;
        case "--root":
            if (!TryReadOptionValue(args, ref i, out var rootValue)) return 1;
            root = Path.GetFullPath(rootValue!);
            rootExplicit = true;
            break;
        case "--registry":
            if (!TryReadOptionValue(args, ref i, out var registryValue)) return 1;
            registryPath = Path.GetFullPath(registryValue!);
            break;
        default:
            if (args[i].StartsWith("--", StringComparison.Ordinal))
            {
                Console.Error.WriteLine($"unknown option: {args[i]}");
                return 1;
            }
            positional.Add(args[i]);
            break;
    }
}

if (positional.Count == 0)
{
    PrintUsage();
    return 1;
}

string command = positional[0];

if (command == "registry-sync")
{
    return RegistrySync();
}

if (registryPath is null)
{
    var workingRegistry = Path.Combine(root, "registry", "registry.json");
    var bundledRegistry = Path.Combine(packageRoot, "registry", "registry.json");

    if (File.Exists(workingRegistry))
    {
        registryPath = workingRegistry;
    }
    else if (File.Exists(bundledRegistry))
    {
        registryPath = bundledRegistry;
        if (!rootExplicit)
        {
            root = packageRoot;
        }
    }
    else
    {
        registryPath = workingRegistry;
    }
}

if (!File.Exists(registryPath))
{
    Console.Error.WriteLine($"registry not found: {registryPath}");
    return 1;
}

using var doc = JsonDocument.Parse(File.ReadAllText(registryPath));
var registryRoot = doc.RootElement;
var byName = new Dictionary<string, JsonElement>();
foreach (var it in registryRoot.GetProperty("items").EnumerateArray())
{
    byName[it.GetProperty("name").GetString()!] = it;
}

switch (command)
{
    case "list":
        Console.WriteLine($"registry: {registryRoot.GetProperty("name").GetString()}");
        foreach (var it in registryRoot.GetProperty("items").EnumerateArray())
        {
            var deps = it.TryGetProperty("registryDependencies", out var d) && d.GetArrayLength() > 0
                ? "  <- " + string.Join(", ", d.EnumerateArray().Select(x => x.GetString()))
                : "";
            var fileCount = it.GetProperty("files").GetArrayLength();
            Console.WriteLine($"  {it.GetProperty("name").GetString(),-20} {it.GetProperty("type").GetString(),-18} {fileCount,3} file(s){deps}");
        }
        return 0;

    case "add":
        if (positional.Count < 2)
        {
            Console.Error.WriteLine("usage: navius-wpf add <name> --to <dir> --namespace <ns> [--root <repo>] [--registry <path>]");
            return 1;
        }
        if (to is null || ns is null)
        {
            Console.Error.WriteLine("usage: navius-wpf add <name> --to <dir> --namespace <ns> [--root <repo>] [--registry <path>]");
            return 1;
        }
        if (!Regex.IsMatch(ns, @"^[_\p{L}][\p{L}\p{Nd}_]*(?:\.[_\p{L}][\p{L}\p{Nd}_]*)*$"))
        {
            Console.Error.WriteLine($"invalid namespace: {ns}");
            return 1;
        }
        return Add(positional[1]);

    default:
        PrintUsage();
        return 1;
}

int Add(string name)
{
    // Topologically resolve registryDependencies (deps first). This is the closure step: an
    // item vendored on its own, without the items it references (e.g. select without
    // anchored-popup and core), leaves dangling types and does not compile.
    var resolved = new List<string>();
    var seen = new HashSet<string>();

    bool Resolve(string n)
    {
        if (seen.Contains(n)) return true;
        if (!byName.TryGetValue(n, out var item))
        {
            Console.Error.WriteLine($"unknown item: {n}");
            return false;
        }
        seen.Add(n);
        if (item.TryGetProperty("registryDependencies", out var deps))
        {
            foreach (var dep in deps.EnumerateArray())
            {
                if (!Resolve(dep.GetString()!)) return false;
            }
        }
        resolved.Add(n);
        return true;
    }

    if (!Resolve(name)) return 1;

    var destinationRoot = Path.GetFullPath(to!);
    var pendingCopies = new List<(string Source, string Destination, string Target)>();
    var destinations = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
    int missing = 0;
    foreach (var n in resolved)
    {
        var item = byName[n];
        Console.WriteLine($"{n}:");
        foreach (var f in item.GetProperty("files").EnumerateArray())
        {
            var srcRel = f.GetProperty("path").GetString()!;
            var tgtRel = f.GetProperty("target").GetString()!;

            string src;
            string dst;
            try
            {
                src = ResolveSourcePath(srcRel);
                dst = ResolvePathUnder(destinationRoot, tgtRel, "target");
            }
            catch (InvalidOperationException ex)
            {
                Console.Error.WriteLine($"  ! {ex.Message}");
                return 1;
            }

            if (!File.Exists(src))
            {
                Console.Error.WriteLine($"  ! missing source: {srcRel} (resolved to {src})");
                missing++;
                continue;
            }

            if (!destinations.Add(dst))
            {
                Console.Error.WriteLine($"  ! duplicate target: {tgtRel}");
                return 1;
            }
            pendingCopies.Add((src, dst, tgtRel));
        }
    }

    if (missing > 0)
    {
        Console.Error.WriteLine("No files were written because the registry closure is incomplete.");
        return 1;
    }

    foreach (var copy in pendingCopies)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(copy.Destination)!);
        var text = File.ReadAllText(copy.Source);
        // Fix theme-dictionary pack URIs before the namespace rewrite: the pack URI regexes
        // match the literal "Navius.Wpf.Primitives;component" / "Navius.Wpf.Ui;component"
        // authority segment, which the namespace rewrite below would otherwise mangle first.
        text = FixThemePackUris(text);
        text = RewriteNamespace(text, ns!);
        File.WriteAllText(copy.Destination, text);
        Console.WriteLine($"  + {copy.Target}");
    }

    Console.WriteLine($"\nAdded '{name}' - {resolved.Count} item(s), {pendingCopies.Count} file(s) -> {to}");
    return 0;
}

string ResolveSourcePath(string sourcePath)
{
    var primaryPath = ResolvePathUnder(root, sourcePath, "source");

    if (File.Exists(primaryPath) || rootExplicit)
    {
        return primaryPath;
    }

    var bundledPath = ResolveBundledSourcePath(sourcePath);
    return bundledPath is not null && File.Exists(bundledPath)
        ? bundledPath
        : primaryPath;
}

string? ResolveBundledSourcePath(string sourcePath)
{
    // Registry-relative files (registry/templates/...) are bundled verbatim next to
    // registry.json (see the bundledRegistry path above). Everything else is a repo-root
    // relative source path (e.g. src/Navius.Wpf.Primitives/Controls/...) bundled under
    // registry-source/ with the same relative path (see the .csproj None/PackagePath entries).
    var normalized = sourcePath.Replace('\\', '/');
    var bundledRoot = normalized.StartsWith("registry/", StringComparison.Ordinal)
        ? packageRoot
        : Path.Combine(packageRoot, "registry-source");
    return ResolvePathUnder(bundledRoot, normalized, "source");
}

string ResolvePathUnder(string basePath, string relativePath, string label)
{
    if (string.IsNullOrWhiteSpace(relativePath) || Path.IsPathRooted(relativePath))
    {
        throw new InvalidOperationException($"invalid {label} path: {relativePath}");
    }

    var fullBase = Path.GetFullPath(basePath);
    var fullPath = Path.GetFullPath(Path.Combine(fullBase, relativePath.Replace('/', Path.DirectorySeparatorChar)));
    var relative = Path.GetRelativePath(fullBase, fullPath);
    if (relative == ".." || relative.StartsWith(".." + Path.DirectorySeparatorChar, StringComparison.Ordinal) || Path.IsPathRooted(relative))
    {
        throw new InvalidOperationException($"{label} path escapes its root: {relativePath}");
    }
    return fullPath;
}

bool TryReadOptionValue(string[] arguments, ref int index, out string? value)
{
    if (index + 1 >= arguments.Length || arguments[index + 1].StartsWith("--", StringComparison.Ordinal))
    {
        Console.Error.WriteLine($"missing value for {arguments[index]}");
        value = null;
        return false;
    }
    value = arguments[++index];
    return true;
}

// pack://application:,,,/Navius.Wpf.Primitives;component/Themes/X.xaml (or the shorthand
// /Navius.Wpf.Primitives;component/Themes/X.xaml) names the compiled brain assembly by name.
// Vendored source has no such assembly - the theme dictionaries land as plain files next to
// each other under <projectDir>/NaviusWpf/Themes/ - so the authority segment collapses to a
// bare, same-folder relative Source.
Regex primitivesPackUri() => new(@"(?:pack://application:,,,)?/Navius\.Wpf\.Primitives;component/Themes/([\w.]+\.xaml)");
Regex uiPackUri() => new(@"(?:pack://application:,,,)?/Navius\.Wpf\.Ui;component/Themes/([\w.]+\.xaml)");

string FixThemePackUris(string text)
{
    text = primitivesPackUri().Replace(text, "$1");
    // Ui-origin theme dictionaries land in the same flattened Themes/ folder as Primitives-origin
    // ones, so they are prefixed to avoid a same-name collision (see registry-sync's theme
    // targeting for the matching "Ui." prefix).
    text = uiPackUri().Replace(text, "Ui.$1");
    return text;
}

string RewriteNamespace(string text, string targetNs)
{
    text = text.Replace("Navius.Wpf.Primitives", $"{targetNs}.NaviusWpf.Primitives");
    text = text.Replace("Navius.Wpf.Ui", $"{targetNs}.NaviusWpf.Ui");
    return text;
}

void PrintUsage()
{
    Console.WriteLine("navius-wpf - copy-paste component registry for Navius.Wpf");
    Console.WriteLine();
    Console.WriteLine("  navius-wpf list [--registry <path>]");
    Console.WriteLine("  navius-wpf add <name> --to <dir> --namespace <ns> [--root <repo>] [--registry <path>]");
    Console.WriteLine("  navius-wpf registry-sync [--root <repo>] [--registry <path>]");
    Console.WriteLine();
    Console.WriteLine("  registry-sync scans src/Navius.Wpf.Primitives and src/Navius.Wpf.Ui and");
    Console.WriteLine("  regenerates registry/registry.json deterministically. Run it after adding a");
    Console.WriteLine("  control family or styled item; the registry is generated, never hand-edited.");
}

// ---------------------------------------------------------------------------------------------
// registry-sync: scan the source tree and regenerate registry/registry.json deterministically.
// ---------------------------------------------------------------------------------------------

int RegistrySync()
{
    var syncRoot = rootExplicit ? root : Directory.GetCurrentDirectory();
    var outPath = registryPath ?? Path.Combine(syncRoot, "registry", "registry.json");

    var primitivesRoot = Path.Combine(syncRoot, "src", "Navius.Wpf.Primitives");
    var uiRoot = Path.Combine(syncRoot, "src", "Navius.Wpf.Ui");
    var controlsDir = Path.Combine(primitivesRoot, "Controls");
    var themesDir = Path.Combine(primitivesRoot, "Themes");
    var uiThemesDir = Path.Combine(uiRoot, "Themes");

    if (!Directory.Exists(controlsDir))
    {
        Console.Error.WriteLine($"registry-sync: not found: {controlsDir}");
        return 1;
    }

    var unclassified = new List<string>();
    var items = new List<PendingItem>();

    // --- "core": the shared base layer every popup/overlay-backed family builds on ---------
    var coreFiles = new List<PendingFile>();
    void AddCoreCs(string dir, string targetPrefix)
    {
        if (!Directory.Exists(dir)) return;
        foreach (var f in Directory.GetFiles(dir, "*.cs", SearchOption.TopDirectoryOnly).OrderBy(x => x, StringComparer.Ordinal))
        {
            coreFiles.Add(new PendingFile(f, "registry:code", $"{targetPrefix}/{Path.GetFileName(f)}"));
        }
    }
    AddCoreCs(Path.Combine(primitivesRoot, "Overlays"), "NaviusWpf/Primitives/Overlays");
    AddCoreCs(Path.Combine(primitivesRoot, "Positioning"), "NaviusWpf/Primitives/Positioning");
    AddCoreCs(Path.Combine(primitivesRoot, "Theming"), "NaviusWpf/Primitives/Theming");
    AddCoreCs(Path.Combine(controlsDir, "Internal"), "NaviusWpf/Primitives/Controls/Internal");
    foreach (var themeName in new[] { "Tokens.Light.xaml", "Tokens.Dark.xaml", "Tokens.HighContrast.xaml", "OverlayBackdrop.xaml" })
    {
        var p = Path.Combine(themesDir, themeName);
        if (File.Exists(p))
        {
            coreFiles.Add(new PendingFile(p, "registry:theme", $"NaviusWpf/Themes/{themeName}"));
        }
    }
    if (coreFiles.Count == 0)
    {
        unclassified.Add("core (Overlays/Positioning/Theming/Controls/Internal): no files found");
    }
    else
    {
        items.Add(new PendingItem("core", "registry:core", "Shared overlay/positioning/theming base layer", coreFiles));
    }

    // --- one item per Controls/ subfolder (a "control family"), excluding Internal (core) ---
    foreach (var dir in Directory.GetDirectories(controlsDir)
                 .Where(d => !string.Equals(Path.GetFileName(d), "Internal", StringComparison.Ordinal))
                 .OrderBy(d => Path.GetFileName(d), StringComparer.Ordinal))
    {
        var folderName = Path.GetFileName(dir)!;
        var csFiles = Directory.GetFiles(dir, "*.cs", SearchOption.AllDirectories);
        if (csFiles.Length == 0)
        {
            unclassified.Add($"src/Navius.Wpf.Primitives/Controls/{folderName} (folder has no .cs files)");
            continue;
        }

        var files = csFiles.OrderBy(f => f, StringComparer.Ordinal)
            .Select(f => new PendingFile(f, "registry:code", $"NaviusWpf/Primitives/Controls/{folderName}/{RelativeUnder(f, dir)}"))
            .ToList();

        AddThemeIfExists(files, themesDir, folderName + ".xaml", "NaviusWpf/Themes/" + folderName + ".xaml");

        items.Add(new PendingItem(Kebab(folderName), "registry:primitive", folderName, files));
    }

    // --- flat control files directly under Controls/ (Tier A wraps + small helpers) ---------
    var flatFamilyMap = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["NaviusButton"] = "Button",
        ["NaviusLabel"] = "Label",
        ["NaviusSeparator"] = "Separator",
        ["NaviusSeparatorAutomationPeer"] = "Separator",
        ["NaviusToggle"] = "Toggle",
        ["NaviusAnchoredPopup"] = "AnchoredPopup",
    };
    var flatGroups = new Dictionary<string, List<string>>(StringComparer.Ordinal);
    foreach (var f in Directory.GetFiles(controlsDir, "*.cs", SearchOption.TopDirectoryOnly).OrderBy(f => f, StringComparer.Ordinal))
    {
        var baseName = Path.GetFileNameWithoutExtension(f);
        if (!flatFamilyMap.TryGetValue(baseName, out var family))
        {
            family = baseName.StartsWith("Navius", StringComparison.Ordinal) ? baseName["Navius".Length..] : baseName;
            unclassified.Add($"src/Navius.Wpf.Primitives/Controls/{baseName}.cs (unmapped flat file; filed under its own item '{Kebab(family)}' - add it to flatFamilyMap in registry-sync if it belongs with an existing family instead)");
        }
        if (!flatGroups.TryGetValue(family, out var list))
        {
            flatGroups[family] = list = new List<string>();
        }
        list.Add(f);
    }
    foreach (var (family, files) in flatGroups.OrderBy(kv => kv.Key, StringComparer.Ordinal))
    {
        var pendingFiles = files.OrderBy(f => f, StringComparer.Ordinal)
            .Select(f => new PendingFile(f, "registry:code", $"NaviusWpf/Primitives/Controls/{Path.GetFileName(f)}"))
            .ToList();
        AddThemeIfExists(pendingFiles, themesDir, family + ".xaml", "NaviusWpf/Themes/" + family + ".xaml");
        items.Add(new PendingItem(Kebab(family), "registry:primitive", family, pendingFiles));
    }

    // --- styled items in src/Navius.Wpf.Ui/ -------------------------------------------------
    var uiScaffoldFiles = new HashSet<string>(StringComparer.Ordinal) { "Class1.cs" };
    var uiSkipDirs = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "Themes", "Properties", "bin", "obj" };

    if (Directory.Exists(uiRoot))
    {
        foreach (var dir in Directory.GetDirectories(uiRoot)
                     .Where(d => !uiSkipDirs.Contains(Path.GetFileName(d)!))
                     .OrderBy(d => Path.GetFileName(d), StringComparer.Ordinal))
        {
            var folderName = Path.GetFileName(dir)!;
            var csFiles = Directory.GetFiles(dir, "*.cs", SearchOption.AllDirectories);
            if (csFiles.Length == 0)
            {
                unclassified.Add($"src/Navius.Wpf.Ui/{folderName} (folder has no .cs files)");
                continue;
            }
            var files = csFiles.OrderBy(f => f, StringComparer.Ordinal)
                .Select(f => new PendingFile(f, "registry:code", $"NaviusWpf/Ui/{folderName}/{RelativeUnder(f, dir)}"))
                .ToList();
            AddThemeIfExists(files, uiThemesDir, folderName + ".xaml", "NaviusWpf/Themes/Ui." + folderName + ".xaml");
            items.Add(new PendingItem(Kebab(folderName), "registry:styled", folderName, files));
        }

        foreach (var f in Directory.GetFiles(uiRoot, "*.cs", SearchOption.TopDirectoryOnly).OrderBy(f => f, StringComparer.Ordinal))
        {
            var fileName = Path.GetFileName(f);
            if (uiScaffoldFiles.Contains(fileName))
            {
                unclassified.Add($"src/Navius.Wpf.Ui/{fileName} (scaffold placeholder, not a styled item; skipped)");
                continue;
            }
            var baseName = Path.GetFileNameWithoutExtension(f);
            var files = new List<PendingFile> { new(f, "registry:code", $"NaviusWpf/Ui/{fileName}") };
            AddThemeIfExists(files, uiThemesDir, baseName + ".xaml", "NaviusWpf/Themes/Ui." + baseName + ".xaml");
            items.Add(new PendingItem(Kebab(baseName), "registry:styled", baseName, files));
        }
    }
    else
    {
        unclassified.Add("src/Navius.Wpf.Ui: directory not found");
    }

    // Charts is intentionally not a registry item: it is a third-party-engine adapter distributed
    // as an optional package (ADR-0004), not Navius-owned source whose compile closure can be
    // vendored. Reconsider only if the CLI later gains generic packageDependencies installation
    // support. If/when it shows up under src/, note it instead of silently registering or ignoring.
    var chartsDir = Path.Combine(syncRoot, "src", "Navius.Wpf.Charts");
    if (Directory.Exists(chartsDir))
    {
        unclassified.Add("src/Navius.Wpf.Charts: found but intentionally excluded (third-party-engine adapter, distributed as an optional package per ADR-0004)");
    }

    // --- dependency closure: which items does each item's source actually reference? --------
    var textCache = new Dictionary<string, string>(StringComparer.Ordinal);
    string TextOf(string path)
    {
        if (!textCache.TryGetValue(path, out var text))
        {
            textCache[path] = text = File.ReadAllText(path);
        }
        return text;
    }

    var typeDecl = new Regex(@"(?m)^\s*(?:public|internal|private|protected)?\s*(?:static\s+|sealed\s+|abstract\s+|partial\s+)*(?:class|interface|struct|record|enum)\s+([A-Za-z_]\w*)");
    var typeDeclarers = new Dictionary<string, SortedSet<string>>(StringComparer.Ordinal);
    foreach (var item in items)
    {
        foreach (var file in item.Files.Where(f => f.Path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase)))
        {
            foreach (Match m in typeDecl.Matches(TextOf(file.Path)))
            {
                var name = m.Groups[1].Value;
                if (!typeDeclarers.TryGetValue(name, out var owners))
                {
                    typeDeclarers[name] = owners = new SortedSet<string>(StringComparer.Ordinal);
                }
                owners.Add(item.Name);
            }
        }
    }

    // Two items can independently declare a type with the same bare name in different
    // namespaces (e.g. Menu/NaviusSelectEventArgs.cs and Select/NaviusSelectEventArgs.cs are
    // deliberately distinct types - the source even calls this out). A bare-name text match
    // can't tell those apart, so an ambiguous name is excluded from inference entirely rather
    // than silently attributed to whichever item happened to be scanned first.
    var typeOwner = new Dictionary<string, string>(StringComparer.Ordinal);
    var ambiguousTypeNames = new List<string>();
    foreach (var (name, owners) in typeDeclarers)
    {
        if (owners.Count == 1)
        {
            typeOwner[name] = owners.Single();
        }
        else
        {
            ambiguousTypeNames.Add($"{name} (declared by {string.Join(", ", owners)}; excluded from dependency inference)");
        }
    }

    // Prose (design-rationale comments like "like NaviusRating uses for its star items", or
    // XAML <!-- --> comments) routinely name a sibling family for context without the code
    // actually needing it compiled in. Comments are stripped before the reference scan so those
    // mentions don't manufacture a registryDependency; only text the compiler sees counts.
    string StripComments(string text)
    {
        text = Regex.Replace(text, @"/\*.*?\*/", "", RegexOptions.Singleline);
        text = Regex.Replace(text, @"//[^\r\n]*", "");
        text = Regex.Replace(text, @"<!--.*?-->", "", RegexOptions.Singleline);
        return text;
    }

    foreach (var item in items)
    {
        var deps = new SortedSet<string>(StringComparer.Ordinal);
        var combinedText = StripComments(string.Join('\n', item.Files.Select(f => TextOf(f.Path))));

        foreach (var (typeName, owner) in typeOwner)
        {
            if (owner == item.Name) continue;
            if (Regex.IsMatch(combinedText, $@"\b{Regex.Escape(typeName)}\b"))
            {
                deps.Add(owner);
            }
        }

        // Safety net: a using directive can pull in "core" behavior (extension methods, enum
        // members) that the type-name scan above would miss.
        if (item.Name != "core" &&
            Regex.IsMatch(combinedText, @"using\s+Navius\.Wpf\.Primitives\.(Overlays|Positioning|Theming)\s*;"))
        {
            deps.Add("core");
        }

        item.RegistryDependencies.AddRange(deps);
    }

    // --- write registry/registry.json + registry/schema.json deterministically -------------
    Directory.CreateDirectory(Path.GetDirectoryName(outPath)!);
    var schemaDir = Path.GetDirectoryName(outPath)!;
    var schemaPath = Path.Combine(schemaDir, "schema.json");
    if (!File.Exists(schemaPath))
    {
        File.WriteAllText(schemaPath, RegistrySchemaJson);
    }

    var itemsArray = new JsonArray();
    foreach (var item in items.OrderBy(i => i.Name, StringComparer.Ordinal))
    {
        var filesArray = new JsonArray();
        foreach (var f in item.Files.OrderBy(f => f.Target, StringComparer.Ordinal))
        {
            filesArray.Add(new JsonObject
            {
                ["path"] = RepoRel(f.Path, syncRoot),
                ["type"] = f.Type,
                ["target"] = f.Target,
            });
        }

        itemsArray.Add(new JsonObject
        {
            ["name"] = item.Name,
            ["type"] = item.Type,
            ["title"] = item.Title,
            ["dependencies"] = new JsonArray(),
            ["registryDependencies"] = new JsonArray(item.RegistryDependencies.Distinct().OrderBy(x => x, StringComparer.Ordinal).Select(d => (JsonNode)d!).ToArray()),
            ["files"] = filesArray,
        });
    }

    var registryObj = new JsonObject
    {
        ["$schema"] = "./schema.json",
        ["name"] = "navius-wpf",
        ["items"] = itemsArray,
    };

    var jsonOptions = new JsonSerializerOptions { WriteIndented = true };
    File.WriteAllText(outPath, registryObj.ToJsonString(jsonOptions) + "\n");

    Console.WriteLine($"registry-sync: wrote {items.Count} item(s) to {outPath}");
    Console.WriteLine($"  core: {(items.Any(i => i.Name == "core") ? "present" : "MISSING")}");
    Console.WriteLine($"  primitive items: {items.Count(i => i.Type == "registry:primitive")}");
    Console.WriteLine($"  styled items: {items.Count(i => i.Type == "registry:styled")}");
    if (unclassified.Count > 0)
    {
        Console.WriteLine();
        Console.WriteLine("Could not classify (or intentionally skipped):");
        foreach (var u in unclassified.OrderBy(x => x, StringComparer.Ordinal))
        {
            Console.WriteLine($"  - {u}");
        }
    }
    if (ambiguousTypeNames.Count > 0)
    {
        Console.WriteLine();
        Console.WriteLine("Ambiguous type names (same bare name declared by multiple items; not used for dependency inference):");
        foreach (var a in ambiguousTypeNames.OrderBy(x => x, StringComparer.Ordinal))
        {
            Console.WriteLine($"  - {a}");
        }
    }
    return 0;
}

void AddThemeIfExists(List<PendingFile> files, string themesDir, string fileName, string target)
{
    var p = Path.Combine(themesDir, fileName);
    if (File.Exists(p))
    {
        files.Add(new PendingFile(p, "registry:theme", target));
    }
}

string RelativeUnder(string file, string dir) =>
    Path.GetRelativePath(dir, file).Replace(Path.DirectorySeparatorChar, '/');

string RepoRel(string absolutePath, string repoRoot) =>
    Path.GetRelativePath(repoRoot, absolutePath).Replace(Path.DirectorySeparatorChar, '/');

string Kebab(string pascal)
{
    if (string.IsNullOrEmpty(pascal)) return pascal;
    var sb = new System.Text.StringBuilder();
    for (int i = 0; i < pascal.Length; i++)
    {
        var c = pascal[i];
        if (char.IsUpper(c) && i > 0 &&
            (char.IsLower(pascal[i - 1]) || (i + 1 < pascal.Length && char.IsLower(pascal[i + 1]))))
        {
            sb.Append('-');
        }
        sb.Append(char.ToLowerInvariant(c));
    }
    return sb.ToString();
}

sealed class PendingFile
{
    public PendingFile(string path, string type, string target)
    {
        Path = path;
        Type = type;
        Target = target;
    }
    public string Path { get; }
    public string Type { get; }
    public string Target { get; }
}

sealed class PendingItem
{
    public PendingItem(string name, string type, string title, List<PendingFile> files)
    {
        Name = name;
        Type = type;
        Title = title;
        Files = files;
    }
    public string Name { get; }
    public string Type { get; }
    public string Title { get; }
    public List<PendingFile> Files { get; }
    public List<string> RegistryDependencies { get; } = new();
}
